apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  openclaw.json: |
    {{- if .Values.configOverride }}
    {{- .Values.configOverride | nindent 4 }}
    {{- else }}
    {{- .Files.Get "files/openclaw.json" | nindent 4 }}
    {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-scripts
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  repo.sh: |
    {{- .Files.Get "files/repo.sh" | nindent 4 }}
