{{- if .Values.weeklyPriceUpdate.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: weekly-price-update
spec:
  schedule: '{{ .Values.weeklyPriceUpdate.schedule }}'
  concurrencyPolicy: Forbid
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: weekly-price-update
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                  - /bin/sh
                  - -c
                  - |
                      set -e
                      echo "Fetching prices..."
                      echo "\n;; $(date -u +%Y-%m-%d)" >> /bean/prices/auto.bean
                      bean-price -v -d $(date -u +%Y-%m-%dT%H:%M:%S) --no-cache --clobber $BEANCOUNT_FILE >> /bean/prices/auto.bean
                      echo "Removing leading zeros..."
                      sed -i 's/\([0-9]*\.[0-9]*[1-9]\)0\+[[:space:]]/\1 /' /bean/prices/auto.bean
                      echo "Formatting the file..."
                      bean-format /bean/prices/auto.bean -o /bean/prices/auto.bean
                      echo "done"

                      {{- if .Values.weeklyPriceUpdate.commitToGit }}
                      if ! command -v git >/dev/null 2>&1; then
                        echo "Git is not installed. Skipping commit process."
                        exit 0
                      fi

                      echo "Checking if /bean is a git repository..."
                      cd /bean || exit 1
                      git config --global --add safe.directory /bean

                      if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
                        echo "/bean is not a git repository. Skipping commit process."
                        exit 0
                      fi

                      echo "Git repository found in /bean. Proceeding with commit..."
                      git config --global user.email "cronjob@example.com"
                      git config --global user.name "Price Update CronJob"
                      git add prices/auto.bean
                      git commit -m "Update prices $(date -u +%Y-%m-%d)"

                      if git push origin main; then
                        echo "Git commit and push completed successfully"
                      else
                        echo "Git push failed"
                        exit 1
                      fi
                      {{- end }}

              volumeMounts:
                - name: bean-volume
                  mountPath: /bean
              env:
                {{- range $i, $val := .Values.env }}
                {{- if $val.value }}
                - name: {{ $val.name | quote }}
                  value: {{ $val.value | quote }}
                {{- else if $val.valueFrom }}
                - name: {{ $val.name | quote }}
                  valueFrom:
                    {{- toYaml $val.valueFrom | nindent 20 }}
                {{- end }}
                {{- end }}
          volumes:
            - name: bean-volume
              {{- toYaml .Values.volume | nindent 14 }}

          restartPolicy: Never

      activeDeadlineSeconds: 300
{{- end }}