{{- if .Values.weeklyPriceUpdate.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: weekly-price-update
spec:
  schedule: '{{ .Values.weeklyPriceUpdate.schedule }}'
  concurrencyPolicy: Forbid
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: weekly-price-update
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                  - /bin/sh
                  - -c
                  - |
                      echo "Fetching prices..." &&
                      echo "\n;; $(date -u +%Y-%m-%d)" >> /bean/prices/auto.bean &&
                      bean-price -v -d $(date -u +%Y-%m-%dT%H:%M:%S) --no-cache --clobber $BEANCOUNT_FILE >> /bean/prices/auto.bean &&
                      echo "Removing leading zeros..." &&
                      sed -i 's/\([0-9]*\.[0-9]*[1-9]\)0\+[[:space:]]/\1 /' /bean/prices/auto.bean &&
                      echo "Formating the file..." &&
                      bean-format /bean/prices/auto.bean -o /bean/prices/auto.bean &&
                      echo "done"

              volumeMounts:
                - name: bean-volume
                  mountPath: /bean
              env:
                {{- range $i, $val := .Values.env }}
                {{- if $val.value }}
                - name: {{ $val.name | quote }}
                  value: {{ $val.value | quote }}
                {{- else if $val.valueFrom }}
                - name: {{ $val.name | quote }}
                  valueFrom:
                    {{- toYaml $val.valueFrom | nindent 20 }}
                {{- end }}
                {{- end }}

          volumes:
            - name: bean-volume
              {{- toYaml .Values.volume | nindent 14 }}

          restartPolicy: OnFailure
      
      activeDeadlineSeconds: 300
{{- end }}