apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: gui
    - port: 8181
      targetPort: 8181
      protocol: TCP
      name: gui-https
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: content-server
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
