name: Lint and Test Helm Chart

on:
    push:
        paths:
            - 'charts/**'

jobs:
    lint-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Lint and Test Chart
              uses: helm/chart-testing-action@v2.7.0
